services:
  shortner-api:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_started
        restart: true
      redis:
        condition: service_started
    ports:
      - "${API_PORT}:8080"
    volumes:
      - ./:/usr/src/app/
    env_file: ".env"
    networks:
      - shortener-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdb_volume:/var/lib/postgresql/data
    networks:
      - shortener-network

  redis:
    image: redis:6.2-alpine
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    expose: 
      - "6379"
    networks:
      - shortener-network

volumes:
  pgdb_volume:
    name: pg_shortener

networks:
  shortener-network:
    name: shortener-network
    driver: bridge