services:
  # shortner-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.main
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "${API_PORT}:8080"
  #   volumes:
  #     - ./:/usr/src/app/
  #   environment:
  #     POSTGRES_DB: shortener
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: pass

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdb_volume:/var/lib/postgresql/data

volumes:
  pgdb_volume:
    name: pg_shortener